FROM copter-4.5.0:5

COPY ./get-gz-garden.sh /home/ardupilot/get-gz-garden.sh
COPY ./get-ap_gz-garden.sh /home/ardupilot/get-ap_gz-garden.sh
RUN ls ~
RUN . ~/get-gz-garden.sh
RUN . ~/get-ap_gz-garden.sh

RUN . ~/.bashrc
